// const NotificationType = {
//     USER_REGISTRATION: 'USER_REGISTRATION',
//     USER_APPROVAL: 'USER_APPROVAL',
//     EXPENSE_ADDED: 'EXPENSE_ADDED',
//     VISITOR_ENTRY: 'VISITOR_ENTRY',
//     MAINTENANCE_REMINDER: 'MAINTENANCE_REMINDER',
//     COMMITTEE_MEETING: 'COMMITTEE_MEETING',
//     GENERAL_ANNOUNCEMENT: 'GENERAL_ANNOUNCEMENT',
//     SECURITY_ALERT: 'SECURITY_ALERT'
//   };
  
//   module.exports = NotificationType;